config/routes.rb
BootstrapReboot::Application.routes.draw do
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/contact', to: 'pages#contact'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  root to: 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
  validates :password, :presence => true, confirmation: true, length: { within: 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate(email, password)
      user = find_by_email(email)
      return nil if user.nil?
      return user if user.has_password?(password)
    end

    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private
    
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash "#{salt}--#{string}"
    end

    def make_salt
      secure_hash "#{Time.now.utc}--#{password}"
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination !"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome for nothing !"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Page"
    if @title.nil?
      "Rails Application flavored with Bootstrap :) "
    else
      "#{@title} #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user = nil
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {})
    gravatar_image_tag(user.email.downcase, alt: user.name, :class => "img-rounded", :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="navbar-inner">
    <ul class="nav">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" href="#" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Profile", current_user %></li>
          <% end %>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_stylesheets_and_javascripts.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets_and_javascripts' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span10 offset1">
          <% flash.each do |key, value| %>
            <div class="alert alert-success"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>    
      </div>
    </div><br><br>
<!--      <%= debug(params) if Rails.env.development? %>
 -->     <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
This is what I'm all about !
<div class="span12"> 
<button class="btn btn-large btn-block btn-primary span4 offset4" type="button">Hola BootStrap !</button>
</div>

app/views/pages/contact.html.erb
Contact

app/views/pages/help.html.erb
This may be a help page, but I am not going to help you !

app/views/pages/home.html.erb
<div class="row">
  <div class="span12"><p class="lead span10 offset1">This is the Home page, You know the only reason I am typing out this text is because I want more text in the home page, I can't think of anything right now, but this would suffice it ! Oh by the way I want the Sign up button at the bottom, Still trying to think some thing to write, hmm..... oh wait how about adding a <b>lead</b> class :troll-face: or I can also increase height by decreasing the <b>span class</b> :D</p></div>
  <div class="span12">
    <br><br>
      <%= link_to "Sign up Now !", signup_path, :class => "span4 offset4 btn-large btn btn-primary btn-block" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved !</h4>
    <% @user.errors.full_messages.each do |msg| %>
      <h6><%= msg %></h6>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<h3 class="text-error">You filthy mudblood ! you must sign up before you can even touch this site</h3>
<%= render 'shared/error_messages' %>
<div class="well transparent span7">
  <%= form_for(@user, :html => { :class => "float-left form-horizontal"}) do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :email%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => "control-label" %>
      <div class="controls">
        <%= f.password_field :password%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, "Confirmation", :class => "control-label" %>
      <div class="controls">
        <%= f.password_field :password_confirmation%>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Sign up", :class => "btn btn-success"%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="span12 well">
  <h1 class="span6 pull-left">
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <div class="well span4 pull-right">
    <strong>Name</strong> <%= @user.name %><br>
    <strong>URL</strong> <%= link_to user_path(@user), @user %>
  </div>
</div>